import CTA from '../components/CTA';
import Icon from '../components/Icon';
import SEO from '../components/SEO';
import SectionHero from '../components/SectionHero';
import SiteLayout from '../layouts/SiteLayout';
import { values } from '../constants/content';
import { tech } from '../constants/site';

export default function About() {
  return (
    <SiteLayout>
      <SEO title="About" path="/about" description="Learn about KodeAura7, a Dehradun digital technology agency building growth systems for ambitious businesses." />
      <SectionHero eyebrow="About KodeAura7" title="We Engineer" gradient="Digital Growth" description="KodeAura7 is a full-service digital technology agency from Dehradun, India. We partner with businesses to design, build, and scale their digital infrastructure." />
      <section className="py-20 md:py-28 border-t border-zinc-900"><div className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-2 gap-16 items-start"><div><p className="font-mono text-xs text-zinc-500 tracking-widest uppercase mb-4">Our Story</p><h2 className="font-display font-semibold text-3xl md:text-4xl tracking-tighter leading-tight mb-8">Built From Passion. Driven by Purpose.</h2><div className="space-y-5 text-zinc-400 leading-relaxed"><p>KodeAura7 was founded with one conviction - that great technology should be accessible to every ambitious business, not just the Fortune 500.</p><p>Today, we're a team of developers, designers, CRM specialists, and digital marketers who obsess over the details that turn a good product into a great one.</p><p>Our edge is our breadth. We think in systems - how your website, your CRM, your ads, and your automations work together to create compounding growth.</p></div></div><div className="glass-panel border border-zinc-800 rounded-3xl p-8 lg:sticky lg:top-28">{[['150+', 'Projects Delivered'], ['4+', 'Years of Experience'], ['2Cr+', 'Revenue for Clients'], ['98%', 'Client Satisfaction']].map(([value, label], i) => <div key={label}><div className={`flex items-baseline justify-between py-5 ${i === 1 ? 'animate-float-delayed' : i === 2 ? 'animate-float-delayed-more' : 'animate-float'}`}><span className="font-display font-semibold text-3xl text-gradient">{value}</span><span className="text-xs uppercase tracking-widest text-zinc-500 font-mono text-right">{label}</span></div>{i < 3 ? <div className="h-px bg-zinc-800" /> : null}</div>)}</div></div></section>
      <section className="py-20 md:py-28 border-t border-zinc-900"><div className="max-w-7xl mx-auto px-6"><div className="text-center mb-14"><h2 className="font-display font-semibold text-3xl md:text-5xl tracking-tighter mb-4">What Drives Us</h2><p className="text-zinc-400 text-lg">Four principles we refuse to compromise on.</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-6">{values.map((v) => <div key={v.title} className="bg-[#111113] rounded-2xl p-8 border border-zinc-800 hover:border-indigo-500/30 hover:shadow-[0_0_30px_rgba(99,102,241,0.07)] transition-all duration-500"><div className="w-12 h-12 rounded-2xl bg-[#18181B] border border-zinc-800 flex items-center justify-center mb-6" style={{ color: v.accent, borderColor: `color-mix(in srgb,${v.accent} 40%,transparent)` }}><Icon icon={v.icon} width={24} /></div><h3 className="font-display text-xl tracking-tight mb-3">{v.title}</h3><p className="text-sm text-zinc-400 leading-relaxed font-extralight">{v.desc}</p></div>)}</div></div></section>
      <section className="py-20 md:py-28 border-t border-zinc-900"><div className="max-w-7xl mx-auto px-6"><div className="text-center mb-14"><h2 className="font-display font-semibold text-3xl md:text-5xl tracking-tighter mb-4">Our Technology Stack</h2><p className="text-zinc-400 text-lg">Built with tools that scale.</p></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">{tech.map((t) => <div key={t.label} className="group bg-[#111113] border border-zinc-800 rounded-2xl p-6 flex flex-col items-center gap-3 hover:border-zinc-600 transition-all duration-300"><Icon icon={t.icon} width={32} className="text-zinc-400 group-hover:text-indigo-400 transition-colors" /><span className="text-xs text-zinc-500 font-mono">{t.label}</span></div>)}</div></div></section>
      <CTA title="Ready to build something extraordinary?" body="Book a free strategy session. No commitment." />
    </SiteLayout>
  );
}
